name: xenfire-support

services:
  bot:
    container_name: xenfire-support
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./config/.env
    volumes:
      - ./config:/app/config:ro
      - ./messages:/app/messages:ro
      - ./.data:/app/.data
